
name: Blog Console CI/CD
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build project
        run:
          npm install;
          npm run build:prod;
          mv dist console;
          mkdir dist
          tar -cvf ./dist/console.tar console;
      - name: Scp
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist
          remote: /data/www
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          concurrency: 20
  deploy:
    needs: [build]
    name: Deploy console
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            cd /data/www
            rm -rf console
            tar -xvf console.tar
            rm -f console.tar
